from pydantic import BaseModel, Field


class AIConfigUpdate(BaseModel):
    ai_default_provider: str = Field(default="codex", pattern="^(codex|remote|local)$")
    ai_publish_provider: str = Field(default="codex", pattern="^(codex|remote|local)$")
    ai_request_timeout_seconds: int = Field(default=120, ge=10, le=600)
    ai_codex_path: str = Field(default="codex")
    ai_codex_home: str = Field(default="")
    ai_codex_model: str = Field(default="gpt-5.6-sol")
    ai_codex_timeout_seconds: int = Field(default=300, ge=10, le=1800)

    transcription_provider: str = Field(default="volcengine", pattern="^(volcengine|local)$")
    transcription_fallback_provider: str = Field(default="")
    volcengine_asr_api_url: str = Field(default="")
    volcengine_asr_api_key: str = Field(default="")
    volcengine_asr_app_key: str = Field(default="")
    volcengine_asr_access_key: str = Field(default="")
    volcengine_asr_resource_id: str = Field(default="volc.bigasr.auc_turbo")
    volcengine_asr_timeout_seconds: int = Field(default=300, ge=30, le=1800)
    volcengine_asr_audio_format: str = Field(default="mp3")

    ai_analysis_remote_base_url: str = Field(default="")
    ai_analysis_remote_api_key: str = Field(default="")
    ai_analysis_remote_model: str = Field(default="deepseek-v4-flash")
    ai_analysis_remote_protocol: str = Field(default="chat_completions")
    ai_analysis_remote_reasoning_effort: str = Field(default="")
    ai_analysis_remote_responses_path: str = Field(default="/v1/responses")
    ai_analysis_remote_disable_response_storage: bool = Field(default=True)
    ai_analysis_request_timeout_seconds: int = Field(default=120, ge=10, le=600)

    ai_publish_remote_base_url: str = Field(default="")
    ai_publish_remote_api_key: str = Field(default="")
    ai_publish_remote_model: str = Field(default="deepseek-v4-flash")
    ai_publish_remote_protocol: str = Field(default="chat_completions")
    ai_publish_remote_reasoning_effort: str = Field(default="")
    ai_publish_remote_responses_path: str = Field(default="/v1/responses")
    ai_publish_remote_disable_response_storage: bool = Field(default=True)
    ai_publish_request_timeout_seconds: int = Field(default=120, ge=10, le=600)

    # Legacy fields are accepted so older pages or scripts do not break.
    ai_remote_base_url: str = Field(default="")
    ai_remote_api_key: str = Field(default="")
    ai_remote_model: str = Field(default="deepseek-v4-flash")
    ai_remote_review_model: str = Field(default="deepseek-v4-flash")
    ai_remote_publish_model: str = Field(default="deepseek-v4-flash")
    ai_remote_protocol: str = Field(default="chat_completions")
    ai_remote_reasoning_effort: str = Field(default="")
    ai_remote_responses_path: str = Field(default="/v1/responses")
    ai_remote_disable_response_storage: bool = Field(default=True)
    ai_local_base_url: str = Field(default="")
    ai_local_api_key: str = Field(default="")
    ai_local_model: str = Field(default="")
    ai_local_protocol: str = Field(default="chat_completions")
    ai_local_fallback_protocol: str = Field(default="")
    ai_local_health_timeout_seconds: int = Field(default=30, ge=3, le=120)
    ai_network_access: str = Field(default="enabled")
    ai_windows_wsl_setup_acknowledged: bool = Field(default=True)
    ai_model_context_window: int = Field(default=1000000, ge=1)
    ai_model_auto_compact_token_limit: int = Field(default=900000, ge=1)
